# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Poc IBK

variables:
- template: variables.yml

steps:

- task: CmdLine@2
  displayName: 'Clone file'
  inputs:
    script: 'git clone https://github.com/jossHD/templates-apic.git'
- task: CmdLine@2
  displayName: 'Login APIC'
  inputs:
    script: 'apic login -s $(server-apic) -r $(region-apic)  -u $(user-apic) -p $(pass-apic)'

- task: CmdLine@2
  displayName: 'Creating new product'
  inputs:
    script: 'apic create:product --title $(product-name) --version 1.0.0 --apis api-lab-toolkit.yaml --filename producto-lab-toolkit2.yaml --gateway-type $(gw-type)'

- task: CmdLine@2
  displayName: 'Pubishing product'
  inputs:
    script: 'apic products:publish producto-lab-toolkit2.yaml -s $(server-apic) --catalog $(catalog) -o $(org-prov) --format json'

- task: CmdLine@2
  displayName: 'Delete file'
  inputs:
    script: 'mrdir /s templates-apic'
