# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Poc IBK

variables:
- template: variables.yml

steps:
- task: CmdLine@2
  displayName: 'Login APIC'
  inputs:
    script: 'apic login -s $(server-apic) -r $(region-apic)  -u $(user-apic) -p $(pass-apic)'

- task: CmdLine@2
  displayName: 'Creating new product'
  inputs:
    script: 'apic create:product --title "$(product-name)" --version 1.0.0 --apis templates/api-lab-toolkit.yaml --filename templates/product-lab-toolkit2.yaml --gateway-type $(gw-type) --output Y'

- task: CmdLine@2
  displayName: 'Pubishing product'
  inputs:
    script: 'apic products:publish templates/product-lab-toolkit2.yaml -s $(server-apic) -c $(catalog) -o $(org-prov) --format json'


