swagger: '2.0'
info:
  title: api-lab-toolkit
  x-ibm-name: api-lab-toolkit
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - operation-switch:
          version: 2.0.0
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /get-string
              execute:
                - map:
                    version: 2.0.0
                    title: map
                    inputs: {}
                    outputs:
                      output:
                        schema:
                          type: string
                        variable: message.body
                        content: application/json
                    actions:
                      - set: output
                        value: '''Hola esta es una prueba para el toolkit'''
          otherwise: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /api-lab-toolkit
paths:
  /get-string:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
