product: '1.0.0'

info:
  name: producto-lab-toolkit
  title: producto-lab-toolkit
  version: 1.0.0

apis:
  'api-lab-toolkit':
    $ref: api-lab-toolkit.yaml

gateways:
  - datapower-api-gateway


visibility:
  view:
    type: public
  subscribe:
    type: authenticated

plans:
  default:
    title: Default Plan
    description: Default Plan
    approval: false
    rate-limit:
      value: 100/hour
      hard-limit: false
